data = [
    {'name': 'Instagram', 'follower_count': 346, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 215, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Facebook', 'follower_count': 294, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Elon Musk', 'follower_count': 149, 'description': 'Entrepreneur', 'country': 'United States'},
    {'name': 'YouTube', 'follower_count': 235, 'description': 'Video sharing platform', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 190, 'description': 'Television personality', 'country': 'United States'},
    {'name': 'Twitter', 'follower_count': 166, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 172, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Snapchat', 'follower_count': 150, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Neymar Jr', 'follower_count': 139, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'TikTok', 'follower_count': 180, 'description': 'Video sharing platform', 'country': 'China'},
    {'name': 'Selena Gomez', 'follower_count': 145, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'LinkedIn', 'follower_count': 110, 'description': 'Professional networking platform', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 157, 'description': 'Actor and wrestler', 'country': 'United States'},
    {'name': 'Pinterest', 'follower_count': 100, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 145, 'description': 'Television personality', 'country': 'United States'},
    {'name': 'WeChat', 'follower_count': 140, 'description': 'Messaging app', 'country': 'China'},
    {'name': 'Beyoncé', 'follower_count': 133, 'description': 'Musician', 'country': 'United States'},
    {'name': 'WhatsApp', 'follower_count': 180, 'description': 'Messaging app', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 125, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Reddit', 'follower_count': 120, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 120, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Tumblr', 'follower_count': 95, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 115, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Quora', 'follower_count': 85, 'description': 'Question-and-answer platform', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 110, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Spotify', 'follower_count': 135, 'description': 'Music streaming service', 'country': 'Sweden'},
    {'name': 'Rihanna', 'follower_count': 130, 'description': 'Musician', 'country': 'Barbados'},
    {'name': 'Medium', 'follower_count': 75, 'description': 'Publishing platform', 'country': 'United States'},
    {'name': 'Shawn Mendes', 'follower_count': 105, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Vimeo', 'follower_count': 60, 'description': 'Video sharing platform', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 100, 'description': 'Musician', 'country': 'United States'},
    {'name': 'SoundCloud', 'follower_count': 90, 'description': 'Music sharing platform', 'country': 'Germany'},
    {'name': 'Cardi B', 'follower_count': 115, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Discord', 'follower_count': 130, 'description': 'Messaging app', 'country': 'United States'},
    {'name': 'Nicki Minaj', 'follower_count': 125, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Twitch', 'follower_count': 110, 'description': 'Live streaming platform', 'country': 'United States'},
    {'name': 'Bruno Mars', 'follower_count': 105, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Flickr', 'follower_count': 55, 'description': 'Photo sharing platform', 'country': 'United States'},
    {'name': 'Ed Sheeran', 'follower_count': 115, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'Clubhouse', 'follower_count': 70, 'description': 'Audio-based social media platform', 'country': 'United States'},
    {'name': 'Drake', 'follower_count': 130, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Telegram', 'follower_count': 140, 'description': 'Messaging app', 'country': 'Russia'},
    {'name': 'Adele', 'follower_count': 120, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'WhatsApp Business', 'follower_count': 100, 'description': 'Messaging app for businesses', 'country': 'United States'},
    {'name': 'Snoop Dogg', 'follower_count': 110, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Slack', 'follower_count': 80, 'description': 'Collaboration platform', 'country': 'United States'},
    {'name': 'Bill Gates', 'follower_count': 125, 'description': 'Entrepreneur', 'country': 'United States'},
    {'name': 'GitHub', 'follower_count': 70, 'description': 'Code hosting platform', 'country': 'United States'},
    {'name': 'Oprah Winfrey', 'follower_count': 130, 'description': 'Television personality', 'country': 'United States'},
    {'name': 'Wikipedia', 'follower_count': 85, 'description': 'Online encyclopedia', 'country': 'United States'}
]


